FROM elasticsearch:8.7.1
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.8-es8.7.1/ltr-plugin-v1.5.8-es8.7.1.zip
